# Windows-ROOT: esta red intercepta TLS; la JVM debe confiar en el almacén de Windows
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStoreType=Windows-ROOT
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
