// Guía de micronutrientes con evidencia. Rangos RDA/AI para adulto (NIH/OMS).
// Dirección: 'min' = no bajar del mínimo diario; 'max' = no pasar del tope.
// Las FUENTES son preferentemente naturales; solo en el sodio se listan
// procesados/marcas, porque ahí el punto es saber DÓNDE se esconde.
// La evidencia se enuncia como asociación en cohortes o resultado de ensayos.

export const MICROS_GUIA = [
  {
    clave: 'fibra', nombre: 'Fibra', unidad: 'g',
    rango: { tipo: 'min', hombres: 38, mujeres: 25 },
    funcion: 'Alimenta la microbiota, regula la glucosa y el colesterol, y sacia.',
    evidencia: 'Cada 8 g más de fibra al día se asocia con 5-27% menos de enfermedad coronaria, diabetes tipo 2 y cáncer colorrectal.',
    fuente: 'Reynolds A, et al. Lancet, 2019 (meta-análisis para la OMS).',
    fuentes: ['Frijol y lentejas (1/2 taza: 7-8 g)', 'Guayaba (3 piezas: 9 g)', 'Avena sin azúcar (1/3 taza: 3 g)', 'Chía (1 cda: 4 g)', 'Nopal y brócoli', 'Tortilla de maíz nixtamalizada'],
  },
  {
    clave: 'calcio', nombre: 'Calcio', unidad: 'mg',
    rango: { tipo: 'min', hombres: 1000, mujeres: 1000 },
    funcion: 'Estructura de huesos y dientes; contracción muscular y señal nerviosa.',
    evidencia: 'Aumentar el calcio de la dieta produce un incremento pequeño de la densidad ósea (~1-2%); la fuente alimentaria es preferible a la suplementación en dosis altas.',
    fuente: 'Tai V, et al. BMJ, 2015 (revisión sistemática).',
    fuentes: ['Sardina con espina (382 mg/100 g)', 'Queso panela (280 mg/ración)', 'Tortilla de maíz nixtamalizada', 'Nopal (164 mg/taza)', 'Amaranto y chía', 'Brócoli, col y verduras verdes', 'Tofu cuajado con calcio'],
  },
  {
    clave: 'hierro', nombre: 'Hierro', unidad: 'mg',
    rango: { tipo: 'min', hombres: 8, mujeres: 18 },
    funcion: 'Transporta oxígeno en la sangre (hemoglobina); su falta causa anemia.',
    evidencia: 'El hierro vegetal (no hemo) se absorbe mucho mejor con vitamina C en la misma comida; el café y el té justo con la comida lo bloquean. Truco: limón sobre las lentejas.',
    fuente: 'Hallberg L, Hulthén L. Am J Clin Nutr, 2000.',
    fuentes: ['Hígado (6.2 mg/100 g)', 'Lentejas y frijol (2-3 mg/ración)', 'Pepitas de calabaza', 'Espinaca (con limón)', 'Carne roja magra', 'Amaranto y tofu', 'Cereal fortificado (p. ej. Corn Flakes) como apoyo'],
  },
  {
    clave: 'magnesio', nombre: 'Magnesio', unidad: 'mg',
    rango: { tipo: 'min', hombres: 400, mujeres: 310 },
    funcion: 'Participa en 300+ reacciones: energía, músculo, nervios y ritmo cardiaco.',
    evidencia: 'Mayor ingesta de magnesio se asocia con menor riesgo de enfermedad cardiovascular, diabetes tipo 2 e ictus en meta-análisis de cohortes.',
    fuente: 'Fang X, et al. BMC Medicine, 2016.',
    fuentes: ['Semillas de calabaza y chía', 'Frijol y lentejas', 'Almendras y cacahuate', 'Espinaca y acelga', 'Amaranto y avena', 'Chocolate oscuro (>70%)'],
  },
  {
    clave: 'zinc', nombre: 'Zinc', unidad: 'mg',
    rango: { tipo: 'min', hombres: 11, mujeres: 8 },
    funcion: 'Inmunidad, cicatrización, síntesis de proteínas y sentido del gusto.',
    evidencia: 'El zinc es central para la respuesta inmune; iniciado a tiempo, acorta la duración del resfriado común en ensayos (efecto de dosis terapéuticas, no dietéticas).',
    fuente: 'Hemilä H. JRSM Open, 2017.',
    fuentes: ['Ostión y mariscos', 'Carne roja', 'Pepitas de calabaza', 'Frijol y garbanzo', 'Nuez y almendra', 'Huevo y lácteos'],
  },
  {
    clave: 'potasio', nombre: 'Potasio', unidad: 'mg',
    rango: { tipo: 'min', hombres: 3400, mujeres: 2600 },
    funcion: 'Regula la presión arterial (contrapeso del sodio) y la función muscular.',
    evidencia: 'Mayor consumo de potasio reduce la presión arterial y se asocia con 24% menos riesgo de ictus.',
    fuente: 'Aburto NJ, et al. BMJ, 2013 (revisión para la OMS).',
    fuentes: ['Frijol y lentejas', 'Plátano y papaya', 'Papa y camote', 'Aguacate', 'Espinaca y acelga', 'Jitomate y agua de coco'],
  },
  {
    clave: 'sodio', nombre: 'Sodio', unidad: 'mg',
    rango: { tipo: 'max', hombres: 2300, mujeres: 2300 },
    funcion: 'Necesario en poca cantidad; en exceso eleva la presión arterial.',
    evidencia: 'Reducir el sodio baja la presión arterial y, con ello, el riesgo cardiovascular. El 70-80% del sodio viene de procesados, no del salero.',
    fuente: 'Aburto NJ, et al. BMJ, 2013 (revisión para la OMS).',
    marca: true,
    fuentes: ['Sopa Maruchan (1180 mg/vaso)', 'Jamón, salchicha y embutidos', 'Quesos madurados', 'Botanas: Doritos, Sabritas', 'Salsa de soya y consomé en polvo', 'Pan de caja y galletas saladas', '"Bebidas hidratantes" (Electrolit)'],
  },
  {
    clave: 'yodo', nombre: 'Yodo', unidad: 'µg',
    rango: { tipo: 'min', hombres: 150, mujeres: 150 },
    funcion: 'Indispensable para las hormonas tiroideas (metabolismo y, en embarazo, neurodesarrollo).',
    evidencia: 'La sal yodada erradicó el bocio endémico; el déficit en el embarazo es la principal causa prevenible de daño cognitivo en el mundo.',
    fuente: 'Zimmermann MB. Endocrine Reviews, 2009.',
    fuentes: ['Sal yodada (la de mesa común en México)', 'Pescado y mariscos', 'Lácteos y huevo', 'Algas (con moderación)'],
  },
  {
    clave: 'selenio', nombre: 'Selenio', unidad: 'µg',
    rango: { tipo: 'min', hombres: 55, mujeres: 55 },
    funcion: 'Antioxidante (enzimas glutatión peroxidasa) y función tiroidea.',
    evidencia: 'Tanto el déficit como el exceso son dañinos: la ventana segura es estrecha, así que basta la comida y sobran los suplementos.',
    fuente: 'Rayman MP. Lancet, 2012.',
    fuentes: ['Nuez de Brasil (¡1-2 al día bastan!)', 'Atún y sardina', 'Huevo', 'Semillas de girasol', 'Carne y pollo'],
  },
  {
    clave: 'folato', nombre: 'Folato (vitamina B9)', unidad: 'µg',
    rango: { tipo: 'min', hombres: 400, mujeres: 400 },
    funcion: 'Formación de ADN y glóbulos rojos; crítico antes y durante el embarazo.',
    evidencia: 'El ácido fólico periconcepcional reduce ~70% los defectos del tubo neural; por eso se fortifica la harina.',
    fuente: 'MRC Vitamin Study. Lancet, 1991 (ensayo clínico).',
    fuentes: ['Lentejas, frijol y garbanzo', 'Espinaca y verduras verdes', 'Aguacate', 'Brócoli y espárrago', 'Naranja', 'Amaranto'],
  },
  {
    clave: 'vitA', nombre: 'Vitamina A', unidad: 'µg',
    rango: { tipo: 'min', hombres: 900, mujeres: 700 },
    funcion: 'Visión, inmunidad y piel. Del vegetal viene como betacaroteno (seguro).',
    evidencia: 'Su déficit es causa prevenible de ceguera infantil; la fuente vegetal (betacaroteno) no da toxicidad, a diferencia de los suplementos altos de retinol.',
    fuente: 'WHO Global prevalence of vitamin A deficiency, 2009.',
    fuentes: ['Hígado', 'Camote y zanahoria', 'Calabaza de castilla', 'Espinaca y verduras verdes', 'Mango y papaya', 'Huevo'],
  },
  {
    clave: 'vitC', nombre: 'Vitamina C', unidad: 'mg',
    rango: { tipo: 'min', hombres: 90, mujeres: 75 },
    funcion: 'Antioxidante, síntesis de colágeno y potencia la absorción del hierro vegetal.',
    evidencia: 'Sostiene la función inmune; la suplementación regular no previene el resfriado en población general, pero sí acorta un poco su duración.',
    fuente: 'Hemilä H, Chalker E. Cochrane, 2013.',
    fuentes: ['Guayaba (¡377 mg/ración!)', 'Chile y pimiento', 'Cítricos: naranja, toronja', 'Fresa y kiwi', 'Brócoli y coliflor', 'Papaya'],
  },
  {
    clave: 'vitD', nombre: 'Vitamina D', unidad: 'µg',
    rango: { tipo: 'min', hombres: 15, mujeres: 15 },
    funcion: 'Absorción de calcio, huesos e inmunidad. Se sintetiza en la piel con el sol.',
    evidencia: 'El bloqueador reduce la síntesis EN LABORATORIO, pero en la vida real quienes lo usan NO muestran déficit (la aplicación es imperfecta y hay exposición incidental). 10-20 min de sol en brazos y piernas varias veces por semana suele bastar — y no dejes el bloqueador: protege del cáncer de piel. En invierno, piel oscura o poca exposición, prioriza pescado y alimentos fortificados.',
    fuente: 'Neale RE, et al. 2019 (ensayo); Holick MF. N Engl J Med, 2007.',
    fuentes: ['Sol con bloqueador (10-20 min, varias veces/semana)', 'Salmón y sardina', 'Yema de huevo', 'Champiñones expuestos a UV', 'Leche y cereales fortificados'],
  },
  {
    clave: 'vitE', nombre: 'Vitamina E', unidad: 'mg',
    rango: { tipo: 'min', hombres: 15, mujeres: 15 },
    funcion: 'Antioxidante liposoluble que protege las membranas celulares.',
    evidencia: 'En la dieta (frutos secos, aceites, aguacate) es beneficiosa; en cambio, la SUPLEMENTACIÓN en dosis altas no reduce la mortalidad y podría aumentarla ligeramente.',
    fuente: 'Miller ER, et al. Annals of Internal Medicine, 2005 (meta-análisis).',
    fuentes: ['Almendras y avellanas', 'Semillas de girasol', 'Aceite de oliva', 'Aguacate', 'Espinaca'],
  },
  {
    clave: 'b12', nombre: 'Vitamina B12', unidad: 'µg',
    rango: { tipo: 'min', hombres: 2.4, mujeres: 2.4 },
    funcion: 'Nervios y glóbulos rojos. SOLO existe en alimentos de origen animal.',
    evidencia: 'La verdura NO aporta B12: en dieta vegana estricta la suplementación es obligatoria para prevenir daño neurológico irreversible.',
    fuente: 'Pawlak R, et al. Nutrition Reviews, 2013.',
    fuentes: ['Hígado (altísimo)', 'Sardina y atún', 'Carne y pollo', 'Huevo', 'Lácteos', 'Alimentos fortificados (si eres vegano)'],
  },
  {
    clave: 'omega3', nombre: 'Omega-3 (EPA + DHA)', unidad: 'mg',
    rango: { tipo: 'min', hombres: 250, mujeres: 250 },
    funcion: 'Grasas del pescado, con efecto antiinflamatorio y cardiovascular.',
    evidencia: 'El pescado graso 2 veces por semana se asocia con menor riesgo cardiovascular. La cápsula de aceite de pescado, en cambio, tiene un beneficio pequeño e inconsistente en prevención primaria.',
    fuente: 'Abdelhamid AS, et al. Cochrane, 2020.',
    fuentes: ['Sardina, salmón y atún', 'Chía y linaza (como ALA)', 'Nuez de Castilla', 'Huevo enriquecido'],
  },
]
