// Compilación de la evidencia citada en Bodymetria, agrupada por sección.
// Cada entrada: referencia + tema. La misma referencia puede aparecer en dos
// secciones si sustenta ideas distintas.

export const PAPERS = [
  {
    seccion: 'Nutrición y micronutrientes',
    refs: [
      { ref: 'Reynolds A, et al. Lancet, 2019.', tema: 'Fibra y menor riesgo cardiometabólico.' },
      { ref: 'Aune D, et al. Int J Epidemiol, 2017.', tema: 'Frutas y verduras y menor mortalidad.' },
      { ref: 'Naghshi S, et al. BMJ, 2020.', tema: 'Proteína vegetal y menor mortalidad.' },
      { ref: 'Tai V, et al. BMJ, 2015.', tema: 'Calcio de la dieta y densidad ósea.' },
      { ref: 'Hallberg L, Hulthén L. Am J Clin Nutr, 2000.', tema: 'Absorción del hierro vegetal con vitamina C.' },
      { ref: 'Fang X, et al. BMC Medicine, 2016.', tema: 'Magnesio y riesgo cardiovascular/diabetes.' },
      { ref: 'Hemilä H. JRSM Open, 2017.', tema: 'Zinc y duración del resfriado.' },
      { ref: 'Aburto NJ, et al. BMJ, 2013.', tema: 'Potasio y sodio y presión arterial.' },
      { ref: 'Zimmermann MB. Endocrine Reviews, 2009.', tema: 'Yodo y función tiroidea.' },
      { ref: 'Rayman MP. Lancet, 2012.', tema: 'Selenio: ventana estrecha entre déficit y exceso.' },
      { ref: 'MRC Vitamin Study. Lancet, 1991.', tema: 'Ácido fólico y defectos del tubo neural.' },
      { ref: 'Hemilä H, Chalker E. Cochrane, 2013.', tema: 'Vitamina C y resfriado.' },
      { ref: 'Neale RE, et al. 2019; Holick MF. NEJM, 2007.', tema: 'Vitamina D, sol y bloqueador.' },
      { ref: 'Miller ER, et al. Ann Intern Med, 2005.', tema: 'Suplementos de vitamina E en dosis altas.' },
      { ref: 'Pawlak R, et al. Nutrition Reviews, 2013.', tema: 'B12 en dietas veganas.' },
      { ref: 'Abdelhamid AS, et al. Cochrane, 2020.', tema: 'Omega-3: pescado vs cápsulas.' },
      { ref: 'Kraus WE, et al. (CALERIE). Lancet Diabetes Endocrinol, 2019.', tema: 'Restricción calórica ligera y marcadores.' },
    ],
  },
  {
    seccion: 'Ejercicio y recomposición corporal',
    refs: [
      { ref: 'Shailendra P, Baldock KL, et al. Am J Prev Med, 2022.', tema: 'Fuerza y mortalidad: máximo beneficio a 30-60 min/semana (curva en J).' },
      { ref: 'Momma H, et al. Br J Sports Med, 2022.', tema: 'Fuerza y menor mortalidad, cáncer y ECV.' },
      { ref: 'Paluch AE, et al. Lancet Public Health, 2022.', tema: 'Pasos diarios y mortalidad.' },
      { ref: 'Morton RW, et al. Br J Sports Med, 2018.', tema: 'Proteína (~1.6 g/kg) e hipertrofia.' },
      { ref: 'Schoenfeld BJ, et al. J Sports Sci, 2017.', tema: 'Volumen semanal e hipertrofia (dosis-respuesta).' },
      { ref: 'Schoenfeld BJ, et al. J Strength Cond Res, 2021.', tema: 'Cargas altas vs moderadas cerca del fallo.' },
      { ref: 'Longland TM, et al. Am J Clin Nutr, 2016.', tema: 'Recomposición: déficit + proteína alta + fuerza.' },
      { ref: 'Willis LH, et al. J Appl Physiol, 2012.', tema: 'Aeróbico vs fuerza vs combinado.' },
      { ref: 'Levine JA. Best Pract Res Clin Endocrinol Metab, 2002.', tema: 'NEAT: actividad no-ejercicio y gasto.' },
      { ref: 'McGrosky A, et al. (incl. Pontzer H). Ann Hum Biol, 2024.', tema: 'Gasto restringido: pastores seminómadas daasanach gastan lo mismo que poblaciones industrializadas pese a moverse mucho más.' },
    ],
  },
  {
    seccion: 'Entrenamiento: rutinas y cardio',
    refs: [
      { ref: 'Androulakis-Korakakis P, et al. Sports Med, 2020.', tema: 'Dosis mínima efectiva de fuerza (base del programa HIT bajo volumen).' },
      { ref: 'Schoenfeld BJ, et al. Sports Med, 2016.', tema: 'Frecuencia: 2×/semana por músculo rinde igual o mejor que 1× (splits).' },
      { ref: 'Plotkin DL, et al. 2023 (preprint/Peer J).', tema: 'Hip thrust y sentadilla crecen el glúteo de forma similar: combinarlos.' },
      { ref: 'Nemoto K, et al. Mayo Clin Proc, 2007.', tema: 'Protocolo japonés: caminata por intervalos 3+3 min y condición física.' },
      { ref: 'Seiler S. Int J Sports Physiol Perform, 2010.', tema: 'Distribución polarizada del cardio: mucha zona 2, poca alta intensidad.' },
      { ref: 'Milanović Z, et al. Sports Med, 2015.', tema: 'HIIT mejora el VO₂máx más que el continuo moderado.' },
      { ref: 'Gibala MJ, et al. J Physiol, 2012.', tema: 'Sprints (SIT): adaptaciones grandes con volumen mínimo.' },
      { ref: 'Markovic G. Br J Sports Med, 2007.', tema: 'Pliometría y salto vertical.' },
      { ref: 'Thomas E, et al. Int J Sports Med, 2018.', tema: 'Dosis semanal de estiramiento y ganancia de rango (flexibilidad).' },
      { ref: 'Behm DG, et al. Appl Physiol Nutr Metab, 2016.', tema: 'Estiramiento estático largo justo antes de explosivo: pequeño costo agudo.' },
      { ref: 'Williams TD, et al. Sports Med, 2017.', tema: 'Periodizar (variar cargas por bloques) gana a no periodizar para 1RM.' },
      { ref: 'Bell L, et al. Front Sports Act Living, 2022.', tema: 'La descarga programada como práctica estándar en fuerza y físico.' },
    ],
  },
  {
    seccion: 'Suplementación',
    refs: [
      { ref: 'Kreider RB, et al. J Int Soc Sports Nutr, 2017.', tema: 'Creatina: eficacia y seguridad.' },
      { ref: 'Morton RW, et al. Br J Sports Med, 2018.', tema: 'Proteína en polvo solo si no llegas a tu meta.' },
      { ref: 'Trexler ET, et al. J Int Soc Sports Nutr, 2015.', tema: 'Beta-alanina en esfuerzos de 1-4 min.' },
      { ref: 'Gonzalez AM, Trexler ET. J Strength Cond Res, 2020.', tema: 'Citrulina malato: evidencia mixta.' },
      { ref: 'Figueroa A, et al. Am J Hypertens, 2011-2012.', tema: 'Sandía/citrulina y presión arterial.' },
      { ref: 'Serban C, et al. J Hypertens, 2015.', tema: 'Jamaica (hibisco) y presión arterial.' },
      { ref: 'Domínguez R, et al. Nutrients, 2017.', tema: 'Betabel (nitratos) y resistencia.' },
      { ref: 'Kuriyama S, et al. JAMA, 2006.', tema: 'Té verde y mortalidad cardiovascular.' },
    ],
  },
  {
    seccion: 'Tendones y tendinopatías',
    refs: [
      { ref: 'Cook JL, Purdam CR. Br J Sports Med, 2009.', tema: 'Modelo del continuum de la tendinopatía (base del manejo por fases).' },
      { ref: 'Rio E, et al. Br J Sports Med, 2015.', tema: 'Isométricos y analgesia en tendinopatía rotuliana.' },
      { ref: 'Kongsgaard M, et al. Scand J Med Sci Sports, 2009.', tema: 'Heavy slow resistance (HSR) en tendón rotuliano.' },
      { ref: 'Beyer R, et al. Am J Sports Med, 2015.', tema: 'HSR vs excéntrico en tendón de Aquiles (ambos funcionan).' },
      { ref: 'Alfredson H, et al. Am J Sports Med, 1998.', tema: 'Protocolo excéntrico clásico para Aquiles.' },
      { ref: 'Silbernagel KG, et al. J Orthop Sports Phys Ther, 2020.', tema: 'Rehabilitación de tendinopatía guiada por síntomas.' },
    ],
  },
  {
    seccion: 'Hipotiroidismo',
    refs: [
      { ref: 'Jonklaas J, et al. (ATA). Thyroid, 2014.', tema: 'Guía de tratamiento del hipotiroidismo con levotiroxina.' },
      { ref: 'Bolk N, et al. Arch Intern Med, 2010.', tema: 'Levotiroxina nocturna vs matutina: mejor absorción de noche.' },
      { ref: 'Benvenga S, et al. Thyroid, 2008.', tema: 'El café reduce la absorción de la levotiroxina.' },
      { ref: 'Winther KH, et al. Nat Rev Endocrinol, 2020.', tema: 'Selenio en enfermedad tiroidea autoinmune: evidencia mixta.' },
      { ref: 'Leung AM, Braverman LE. Nat Rev Endocrinol, 2014.', tema: 'El exceso de yodo puede inducir o empeorar la disfunción tiroidea.' },
    ],
  },
  {
    seccion: 'Digestivo: dieta baja en FODMAP',
    refs: [
      { ref: 'Gibson PR, Shepherd SJ. J Gastroenterol Hepatol, 2010.', tema: 'El enfoque FODMAP original (Monash University).' },
      { ref: 'Muir JG, et al. J Agric Food Chem, 2007 y 2009.', tema: 'Medición del contenido FODMAP de los alimentos (base de las porciones).' },
      { ref: 'Halmos EP, et al. Gastroenterology, 2014.', tema: 'Ensayo controlado: la dieta baja en FODMAP reduce los síntomas del SII.' },
      { ref: 'Böhn L, et al. Gastroenterology, 2015.', tema: 'Baja en FODMAP vs consejo dietético tradicional en SII (eficacia comparable).' },
      { ref: 'Eswaran SL, et al. Am J Gastroenterol, 2016.', tema: 'Ensayo en SII con diarrea: mejora de dolor y evacuaciones.' },
      { ref: 'Black CJ, et al. Gut, 2022.', tema: 'Meta-análisis en red: la baja en FODMAP es la dieta mejor clasificada para SII.' },
      { ref: 'Whelan K, et al. J Hum Nutr Diet, 2018.', tema: 'El protocolo de 3 etapas: eliminación, reintroducción y personalización.' },
      { ref: 'Tuck C, Barrett J. J Gastroenterol Hepatol, 2017.', tema: 'Cómo hacer los retos de reintroducción (dosis crecientes y lavado).' },
      { ref: 'Staudacher HM, et al. J Nutr, 2012; Gastroenterology, 2017.', tema: 'La eliminación prolongada reduce bifidobacterias: no quedarse en la etapa 1.' },
      { ref: 'O’Keeffe M, et al. Neurogastroenterol Motil, 2018.', tema: 'Seguimiento a largo plazo: la dieta personalizada mantiene el beneficio.' },
      { ref: 'Bellini M, et al. Nutrients, 2020.', tema: 'Limitaciones y adecuación nutricional de la dieta en el mundo real.' },
      { ref: 'Lacy BE, et al. Gastroenterology, 2016 (Roma IV).', tema: 'Criterios diagnósticos del síndrome de intestino irritable.' },
    ],
  },
  {
    seccion: 'Sueño',
    refs: [
      { ref: 'Cappuccio FP, et al. Sleep, 2010.', tema: 'Duración del sueño y mortalidad (óptimo 7-8 h).' },
      { ref: 'Irish LA, et al. Sleep Med Rev, 2015.', tema: 'Higiene del sueño y horario regular.' },
      { ref: 'Drake C, et al. J Clin Sleep Med, 2013.', tema: 'Cafeína hasta 6 h antes reduce el sueño.' },
      { ref: 'Chang AM, et al. PNAS, 2015.', tema: 'Pantallas nocturnas y melatonina.' },
      { ref: 'Okamoto-Mizuno K, Mizuno K. J Physiol Anthropol, 2012.', tema: 'Temperatura del cuarto y calidad del sueño.' },
      { ref: 'Stutz J, et al. Sports Med, 2019.', tema: 'Ejercicio y calidad del sueño.' },
      { ref: 'Ebrahim IO, et al. Alcohol Clin Exp Res, 2013.', tema: 'Alcohol y fragmentación del sueño.' },
      { ref: 'Brooks A, Lack L. Sleep, 2006.', tema: 'Siestas cortas y alerta.' },
    ],
  },
  {
    seccion: 'Hábitos y longevidad (app)',
    refs: [
      { ref: 'Warburton DER, et al. CMAJ, 2006.', tema: 'Beneficios de la actividad física.' },
      { ref: 'Dmitrieva NI, et al. eBioMedicine, 2023.', tema: 'Hidratación y envejecimiento biológico.' },
      { ref: 'Goyal M, et al. JAMA Intern Med, 2014.', tema: 'Meditación y estrés/ansiedad.' },
      { ref: 'Bavishi A, Slade MD, Levy BR. Soc Sci Med, 2016.', tema: 'Leer libros y supervivencia.' },
      { ref: 'Twenge JM, Campbell WK. Prev Med Rep, 2018.', tema: 'Tiempo de pantalla y bienestar.' },
    ],
  },
]
